//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:pertamina:osds:BapiPackageMultiClient", ConfigurationName="mi_osReadTableMC_PXD.mi_osReadTableMC")]
    public interface mi_osReadTableMC {
        
        // CODEGEN: Generating message contract since the operation mi_osReadTableMC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCResponse mi_osReadTableMC(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCResponse> mi_osReadTableMCAsync(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pertamina:osds:BapiPackageMultiClient")]
    public partial class dt_ReadTableMC_Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cLIENTField;
        
        private string qUERY_TABLEField;
        
        private string dELIMITERField;
        
        private string nO_DATAField;
        
        private string rOWSKIPSField;
        
        private string rOWCOUNTField;
        
        private dt_ReadTableMC_RequestOPTIONS[] oPTIONSField;
        
        private dt_ReadTableMC_RequestFIELDS[] fIELDSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CLIENT {
            get {
                return this.cLIENTField;
            }
            set {
                this.cLIENTField = value;
                this.RaisePropertyChanged("CLIENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string QUERY_TABLE {
            get {
                return this.qUERY_TABLEField;
            }
            set {
                this.qUERY_TABLEField = value;
                this.RaisePropertyChanged("QUERY_TABLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DELIMITER {
            get {
                return this.dELIMITERField;
            }
            set {
                this.dELIMITERField = value;
                this.RaisePropertyChanged("DELIMITER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NO_DATA {
            get {
                return this.nO_DATAField;
            }
            set {
                this.nO_DATAField = value;
                this.RaisePropertyChanged("NO_DATA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ROWSKIPS {
            get {
                return this.rOWSKIPSField;
            }
            set {
                this.rOWSKIPSField = value;
                this.RaisePropertyChanged("ROWSKIPS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ROWCOUNT {
            get {
                return this.rOWCOUNTField;
            }
            set {
                this.rOWCOUNTField = value;
                this.RaisePropertyChanged("ROWCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OPTIONS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public dt_ReadTableMC_RequestOPTIONS[] OPTIONS {
            get {
                return this.oPTIONSField;
            }
            set {
                this.oPTIONSField = value;
                this.RaisePropertyChanged("OPTIONS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FIELDS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public dt_ReadTableMC_RequestFIELDS[] FIELDS {
            get {
                return this.fIELDSField;
            }
            set {
                this.fIELDSField = value;
                this.RaisePropertyChanged("FIELDS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:osds:BapiPackageMultiClient")]
    public partial class dt_ReadTableMC_RequestOPTIONS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TEXT {
            get {
                return this.tEXTField;
            }
            set {
                this.tEXTField = value;
                this.RaisePropertyChanged("TEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:pertamina:osds:BapiPackageMultiClient")]
    public partial class dt_ReadTableMC_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cLIENTField;
        
        private string eRROR_CODESField;
        
        private dt_ReadTableMC_ResponseFIELDS[] fIELDSField;
        
        private dt_ReadTableMC_ResponseDATA[] dATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CLIENT {
            get {
                return this.cLIENTField;
            }
            set {
                this.cLIENTField = value;
                this.RaisePropertyChanged("CLIENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ERROR_CODES {
            get {
                return this.eRROR_CODESField;
            }
            set {
                this.eRROR_CODESField = value;
                this.RaisePropertyChanged("ERROR_CODES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FIELDS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public dt_ReadTableMC_ResponseFIELDS[] FIELDS {
            get {
                return this.fIELDSField;
            }
            set {
                this.fIELDSField = value;
                this.RaisePropertyChanged("FIELDS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public dt_ReadTableMC_ResponseDATA[] DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
                this.RaisePropertyChanged("DATA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:osds:BapiPackageMultiClient")]
    public partial class dt_ReadTableMC_ResponseFIELDS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fIELDNAMEField;
        
        private string oFFSETField;
        
        private string lENGTHField;
        
        private string tYPEField;
        
        private string fIELDTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FIELDNAME {
            get {
                return this.fIELDNAMEField;
            }
            set {
                this.fIELDNAMEField = value;
                this.RaisePropertyChanged("FIELDNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OFFSET {
            get {
                return this.oFFSETField;
            }
            set {
                this.oFFSETField = value;
                this.RaisePropertyChanged("OFFSET");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LENGTH {
            get {
                return this.lENGTHField;
            }
            set {
                this.lENGTHField = value;
                this.RaisePropertyChanged("LENGTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FIELDTEXT {
            get {
                return this.fIELDTEXTField;
            }
            set {
                this.fIELDTEXTField = value;
                this.RaisePropertyChanged("FIELDTEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:osds:BapiPackageMultiClient")]
    public partial class dt_ReadTableMC_ResponseDATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string waField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string WA {
            get {
                return this.waField;
            }
            set {
                this.waField = value;
                this.RaisePropertyChanged("WA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:pertamina:osds:BapiPackageMultiClient")]
    public partial class dt_ReadTableMC_RequestFIELDS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fIELDNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FIELDNAME {
            get {
                return this.fIELDNAMEField;
            }
            set {
                this.fIELDNAMEField = value;
                this.RaisePropertyChanged("FIELDNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mi_osReadTableMCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pertamina:osds:BapiPackageTesting", Order=0)]
        public SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.dt_ReadTableMC_Request mt_ReadTableMC_Request;
        
        public mi_osReadTableMCRequest() {
        }
        
        public mi_osReadTableMCRequest(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.dt_ReadTableMC_Request mt_ReadTableMC_Request) {
            this.mt_ReadTableMC_Request = mt_ReadTableMC_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mi_osReadTableMCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:pertamina:osds:BapiPackageTesting", Order=0)]
        public SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.dt_ReadTableMC_Response mt_ReadTableMC_Response;
        
        public mi_osReadTableMCResponse() {
        }
        
        public mi_osReadTableMCResponse(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.dt_ReadTableMC_Response mt_ReadTableMC_Response) {
            this.mt_ReadTableMC_Response = mt_ReadTableMC_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mi_osReadTableMCChannel : SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mi_osReadTableMCClient : System.ServiceModel.ClientBase<SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMC>, SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMC {
        
        public mi_osReadTableMCClient() {
        }
        
        public mi_osReadTableMCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mi_osReadTableMCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mi_osReadTableMCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mi_osReadTableMCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCResponse SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMC.mi_osReadTableMC(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest request) {
            return base.Channel.mi_osReadTableMC(request);
        }
        
        public SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.dt_ReadTableMC_Response mi_osReadTableMC(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.dt_ReadTableMC_Request mt_ReadTableMC_Request) {
            SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest inValue = new SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest();
            inValue.mt_ReadTableMC_Request = mt_ReadTableMC_Request;
            SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCResponse retVal = ((SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMC)(this)).mi_osReadTableMC(inValue);
            return retVal.mt_ReadTableMC_Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCResponse> SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMC.mi_osReadTableMCAsync(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest request) {
            return base.Channel.mi_osReadTableMCAsync(request);
        }
        
        public System.Threading.Tasks.Task<SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCResponse> mi_osReadTableMCAsync(SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.dt_ReadTableMC_Request mt_ReadTableMC_Request) {
            SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest inValue = new SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMCRequest();
            inValue.mt_ReadTableMC_Request = mt_ReadTableMC_Request;
            return ((SCMONLINE.SAPSynchronizer.mi_osReadTableMC_PXD.mi_osReadTableMC)(this)).mi_osReadTableMCAsync(inValue);
        }
    }
}
