using Serenity.Navigation;
using MyPages = SCMONLINE.Procurement.Pages;

[assembly: NavigationMenu(7000, "Master", icon: "fa-cubes")]
[assembly: NavigationLink(int.MaxValue, "Master/Address", typeof(MyPages.AddressController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Address Type", typeof(MyPages.AddressTypeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Committee Member", typeof(MyPages.CommitteeMemberController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Committee Role", typeof(MyPages.CommitteeRoleController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Committee Type", typeof(MyPages.CommitteeTypeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Contract Type", typeof(MyPages.ContractTypeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Currency", typeof(MyPages.CurrencyController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Doc Submit Method", typeof(MyPages.DocSubmitMethodController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Document Status", typeof(MyPages.DocumentStatusController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Evaluation Conclusion", typeof(MyPages.EvaluationConclusionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Evaluation Conclusion Item", typeof(MyPages.EvaluationConclusionItemController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Order Type", typeof(MyPages.OrderTypeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Bidder", typeof(MyPages.ProcParticipantController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Bidder Item", typeof(MyPages.ProcParticipantItemController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Proc Status", typeof(MyPages.ProcStatusController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Proc Value Range", typeof(MyPages.ProcValueRangeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Purchase Requisition", typeof(MyPages.PurchaseRequisitionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Rfq Item", typeof(MyPages.RfqItemController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Rfq Item Text", typeof(MyPages.RfqItemTextController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Rfq Text", typeof(MyPages.RfqTextController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Vendor", typeof(MyPages.VendorController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Vendor Address", typeof(MyPages.VendorAddressController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Procurement Type", typeof(MyPages.ProcurementTypeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Procurement Method", typeof(MyPages.ProcurementMethodController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Purch Doc Text Ref", typeof(MyPages.PurchDocTextRefController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Vendor Representative", typeof(MyPages.VendorRepresentativeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Committee Role", typeof(MyPages.CommitteeRoleController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Committee Type", typeof(MyPages.CommitteeTypeController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Committee Member Mapping", typeof(MyPages.CommitteeMemberMappingController), icon: null)]

[assembly: NavigationMenu(1001, "Procurement", icon: "fa-cube")]
[assembly: NavigationLink(int.MaxValue, "Procurement/F1 Pemilihan & Penyesuaian Bidder List", typeof(MyPages.F1_BLSelectionAdjustmentController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F2 Pembuatan Dokumen Pengadaan", typeof(MyPages.F2_ProcurementDocCreationController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F3 Pembuatan RFQ", typeof(MyPages.F3_CreateRFQController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F3 1 Input Harga Owner Estimate", typeof(MyPages.F3_1_InputOwnerEstimateController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F4 Aanwijzing", typeof(MyPages.F4_AanwijzingController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F5 Pengiriman dokumen penawaran", typeof(MyPages.F5_SubmitTenderDocumentController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F6 Pembukaan dokumen penawaran", typeof(MyPages.F6_OpenTenderDocumentController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F7 Evaluasi Penawaran", typeof(MyPages.F7_TenderEvaluationController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F19 Committee Approval", typeof(MyPages.F19_CommitteeApprovalController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F8 Klarifikasi Teknis", typeof(MyPages.F8_TechnicalClarificationController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F9 Evaluasi Harga", typeof(MyPages.F9_PriceEvaluationController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F10 Negosiasi", typeof(MyPages.F10_NegotiationController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F11 Pengusulan calon pemenang", typeof(MyPages.F11_ProposeWinnerController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F12 Proc As", typeof(MyPages.F12_ProcAsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F13 Keputusan Penetapan", typeof(MyPages.F13_ProcResultDecisionController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F14 Pengumuman Pemenang", typeof(MyPages.F14_WinnerAnnouncementController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F15 Proses Sanggahan", typeof(MyPages.F15_ObjectionProcessController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F16 Penunjukan Pemenang", typeof(MyPages.F16_WinnerDesignationController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F17 Upload Dokumen PO", typeof(MyPages.F17_PurchOrderDocUploadController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Procurement/F20 Purchase Requisition Tracking", typeof(MyPages.F20_PurchaseRequisitionTrackingController), icon: null)]

[assembly: NavigationMenu(1021, "Report Procurement", icon: "fa-file-text-o")]
[assembly: NavigationLink(int.MaxValue, "Report Procurement/R1 Bidder List Selection Adjustment", typeof(MyPages.F1_BLSelectionAdjustmentController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Report Procurement/R2 E-mail Dokumen Pengadaan", typeof(MyPages.F3_CreateRFQController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Report Procurement/R3 Berita Acara Penjelasan Pekerjaan", typeof(MyPages.F4_AanwijzingController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Report Procurement/R4 Berita Acara Pembukaan Dokumen Penawaran Sampul I", typeof(MyPages.F6_OpenTenderDocumentController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Report Procurement/R5 Berita Acara Evaluasi Negosiasi", typeof(MyPages.F10_NegotiationController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Report Procurement/R6 Berita Acara Hasil Pengadaan", typeof(MyPages.F11_ProposeWinnerController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Report Procurement/R7 SPPL", typeof(MyPages.F16_WinnerDesignationController), icon: null)]

//[assembly: NavigationLink(int.MaxValue, "Procurement/Report Viewer", typeof(MyPages.ReportViewerAController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Report F1", typeof(MyPages.BudgetReportController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Proc Pr", typeof(MyPages.ProcPrController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Vendor Lookup View", typeof(MyPages.VendorLookupViewController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Buyer Lookup View", typeof(MyPages.BuyerLookupViewController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Approval Authority Range", typeof(MyPages.ApprovalAuthorityRangeController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Characteristic Description", typeof(MyPages.CharacteristicDescriptionController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Characteristic Value", typeof(MyPages.CharacteristicValueController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/F20 Proc Pr", typeof(MyPages.F20_ProcPrController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/F20 Procurement", typeof(MyPages.F20_ProcurementController), icon: null)]

//[assembly: NavigationLink(int.MaxValue, "Procurement/F19 Committee Member", typeof(MyPages.F19_CommitteeMemberController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/F19 Proc Participant", typeof(MyPages.F19_ProcParticipantController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/F19 Proc Participant Item", typeof(MyPages.F19_ProcParticipantItemController), icon: null)]

//[assembly: NavigationLink(int.MaxValue, "Procurement/F10 Proc Participant", typeof(MyPages.F10_ProcParticipantController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Procurement/Procurement", typeof(MyPages.ProcurementController), icon: null)]
