namespace SCMONLINE.Default {
    export interface ProcurementForm {
        ProcurementTypeId: Serenity.StringEditor;
        Status: Serenity.StringEditor;
        CollectiveNumber: Serenity.StringEditor;
        Title: Serenity.StringEditor;
        Classification: Serenity.StringEditor;
        Qualification: Serenity.StringEditor;
        RequestedBy: Serenity.StringEditor;
        RequestorPosition: Serenity.StringEditor;
        ApprovedBy: Serenity.StringEditor;
        ApproverPosition: Serenity.StringEditor;
        SapBidderListCreatedBy: Serenity.StringEditor;
        SapBidderListCreatedDate: Serenity.DateEditor;
        CreatedBy: Serenity.StringEditor;
        CreatedDate: Serenity.DateEditor;
        GuaranteePercentage: Serenity.DecimalEditor;
        OfficeAddress: Serenity.IntegerEditor;
        ProcValueRangeId: Serenity.IntegerEditor;
        CommitteeTypeId: Serenity.IntegerEditor;
        PerformanceGuaranteeRequired: Serenity.BooleanEditor;
        TenderPeriod: Serenity.IntegerEditor;
        DeliveryTime: Serenity.IntegerEditor;
        DestinationId: Serenity.IntegerEditor;
        ContractTypeId: Serenity.IntegerEditor;
        CurrencyId: Serenity.StringEditor;
        DocSubmitMethodId: Serenity.IntegerEditor;
        AanwijzingExists: Serenity.BooleanEditor;
        AanwijzingDate: Serenity.DateEditor;
        AanwijzingClosingDate: Serenity.DateEditor;
        AanwijzingLocation: Serenity.StringEditor;
        AanwijzingClosingLocation: Serenity.StringEditor;
        AanwijzingSecretary: Serenity.StringEditor;
        TechnicalExplanation: Serenity.StringEditor;
        AdministrativeExplanation: Serenity.StringEditor;
        OtherExplanation: Serenity.StringEditor;
        AanwijzingSummary: Serenity.StringEditor;
        FieldSurveyExists: Serenity.BooleanEditor;
        FieldSurveyAddress: Serenity.StringEditor;
        ItbDocumentFile: Serenity.StringEditor;
        ItbDocumentName: Serenity.StringEditor;
        RksDocumentFile: Serenity.StringEditor;
        RksDocumentName: Serenity.StringEditor;
        TenderDocSubmitOpenDate: Serenity.DateEditor;
        TenderDocSubmitCloseDate: Serenity.DateEditor;
        OrderTypeId: Serenity.StringEditor;
        PurchDocNum: Serenity.StringEditor;
        RfqDate: Serenity.DateEditor;
        QuotationDeadline: Serenity.DateEditor;
        PurchGroup: Serenity.StringEditor;
        PrNo: Serenity.StringEditor;
        AuthPersonName: Serenity.StringEditor;
        AuthPosition: Serenity.StringEditor;
        HeaderText: Serenity.StringEditor;
        HeaderNote: Serenity.StringEditor;
        WorkDescription: Serenity.StringEditor;
        BankKey: Serenity.StringEditor;
        PoCover: Serenity.StringEditor;
        DeliveryAddress: Serenity.StringEditor;
        ToPTargVal: Serenity.StringEditor;
        YourReference: Serenity.StringEditor;
        OurReference: Serenity.StringEditor;
        SalesPerson: Serenity.StringEditor;
        Telephone: Serenity.StringEditor;
        ValidityStart: Serenity.DateEditor;
        ValidityEnd: Serenity.DateEditor;
        ItemInterval: Serenity.DecimalEditor;
        SubItemInterval: Serenity.DecimalEditor;
        Warranty: Serenity.DateEditor;
        Language: Serenity.StringEditor;
        EvaluationClosingPriceDate: Serenity.DateEditor;
        ReviewOeRequired: Serenity.BooleanEditor;
        ProcAgreement: Serenity.BooleanEditor;
        ProcAgreementDate: Serenity.DateEditor;
        ProcAsRequired: Serenity.BooleanEditor;
        ProcAsApproved: Serenity.BooleanEditor;
        ProcAsApprovedDate: Serenity.DateEditor;
        ProcAsDesc: Serenity.StringEditor;
        FinalConclusionDesc: Serenity.StringEditor;
        WinnerNominationDate: Serenity.DateEditor;
        ObjectionCloseDate: Serenity.DateEditor;
        PoDocName: Serenity.StringEditor;
        TemporaryPic: Serenity.StringEditor;
        PoNumber: Serenity.StringEditor;
        PoDocFile: Serenity.StringEditor;
        F1SubmitDate: Serenity.DateEditor;
        F1SubmitBy: Serenity.StringEditor;
        F2SubmitDate: Serenity.DateEditor;
        F2SubmitBy: Serenity.StringEditor;
        F3SubmitDate: Serenity.DateEditor;
        F3SubmitBy: Serenity.StringEditor;
        F31SubmitDate: Serenity.DateEditor;
        F31SubmitBy: Serenity.StringEditor;
        F4SubmitDate: Serenity.DateEditor;
        F4SubmitBy: Serenity.StringEditor;
        F5SubmitDate: Serenity.DateEditor;
        F5SubmitBy: Serenity.StringEditor;
        F6SubmitDate: Serenity.DateEditor;
        F6SubmitBy: Serenity.StringEditor;
        F7SubmitDate: Serenity.DateEditor;
        F7SubmitBy: Serenity.StringEditor;
        F8SubmitDate: Serenity.DateEditor;
        F8SubmitBy: Serenity.StringEditor;
        F9SubmitDate: Serenity.DateEditor;
        F9SubmitBy: Serenity.StringEditor;
        F10SubmitDate: Serenity.DateEditor;
        F10SubmitBy: Serenity.StringEditor;
        F11SubmitDate: Serenity.DateEditor;
        F11SubmitBy: Serenity.StringEditor;
        F12SubmitDate: Serenity.DateEditor;
        F12SubmitBy: Serenity.StringEditor;
        F13SubmitDate: Serenity.DateEditor;
        F13SubmitBy: Serenity.StringEditor;
        F14SubmitDate: Serenity.DateEditor;
        F14SubmitBy: Serenity.StringEditor;
        F15SubmitDate: Serenity.DateEditor;
        F15SubmitBy: Serenity.StringEditor;
        F16SubmitDate: Serenity.DateEditor;
        F16SubmitBy: Serenity.StringEditor;
        F17SubmitDate: Serenity.DateEditor;
        F17SubmitBy: Serenity.StringEditor;
        F19SubmitDate: Serenity.DateEditor;
        F19SubmitBy: Serenity.StringEditor;
        ProcurementMethodId: Serenity.StringEditor;
        District: Serenity.StringEditor;
        Csms: Serenity.StringEditor;
        MinScore: Serenity.StringEditor;
        ProcRejectTender: Serenity.BooleanEditor;
        ProcRejectTenderDesc: Serenity.StringEditor;
    }

    export class ProcurementForm extends Serenity.PrefixedContext {
        static formKey = 'Default.Procurement';
        private static init: boolean;

        constructor(prefix: string) {
            super(prefix);

            if (!ProcurementForm.init)  {
                ProcurementForm.init = true;

                var s = Serenity;
                var w0 = s.StringEditor;
                var w1 = s.DateEditor;
                var w2 = s.DecimalEditor;
                var w3 = s.IntegerEditor;
                var w4 = s.BooleanEditor;

                Q.initFormType(ProcurementForm, [
                    'ProcurementTypeId', w0,
                    'Status', w0,
                    'CollectiveNumber', w0,
                    'Title', w0,
                    'Classification', w0,
                    'Qualification', w0,
                    'RequestedBy', w0,
                    'RequestorPosition', w0,
                    'ApprovedBy', w0,
                    'ApproverPosition', w0,
                    'SapBidderListCreatedBy', w0,
                    'SapBidderListCreatedDate', w1,
                    'CreatedBy', w0,
                    'CreatedDate', w1,
                    'GuaranteePercentage', w2,
                    'OfficeAddress', w3,
                    'ProcValueRangeId', w3,
                    'CommitteeTypeId', w3,
                    'PerformanceGuaranteeRequired', w4,
                    'TenderPeriod', w3,
                    'DeliveryTime', w3,
                    'DestinationId', w3,
                    'ContractTypeId', w3,
                    'CurrencyId', w0,
                    'DocSubmitMethodId', w3,
                    'AanwijzingExists', w4,
                    'AanwijzingDate', w1,
                    'AanwijzingClosingDate', w1,
                    'AanwijzingLocation', w0,
                    'AanwijzingClosingLocation', w0,
                    'AanwijzingSecretary', w0,
                    'TechnicalExplanation', w0,
                    'AdministrativeExplanation', w0,
                    'OtherExplanation', w0,
                    'AanwijzingSummary', w0,
                    'FieldSurveyExists', w4,
                    'FieldSurveyAddress', w0,
                    'ItbDocumentFile', w0,
                    'ItbDocumentName', w0,
                    'RksDocumentFile', w0,
                    'RksDocumentName', w0,
                    'TenderDocSubmitOpenDate', w1,
                    'TenderDocSubmitCloseDate', w1,
                    'OrderTypeId', w0,
                    'PurchDocNum', w0,
                    'RfqDate', w1,
                    'QuotationDeadline', w1,
                    'PurchGroup', w0,
                    'PrNo', w0,
                    'AuthPersonName', w0,
                    'AuthPosition', w0,
                    'HeaderText', w0,
                    'HeaderNote', w0,
                    'WorkDescription', w0,
                    'BankKey', w0,
                    'PoCover', w0,
                    'DeliveryAddress', w0,
                    'ToPTargVal', w0,
                    'YourReference', w0,
                    'OurReference', w0,
                    'SalesPerson', w0,
                    'Telephone', w0,
                    'ValidityStart', w1,
                    'ValidityEnd', w1,
                    'ItemInterval', w2,
                    'SubItemInterval', w2,
                    'Warranty', w1,
                    'Language', w0,
                    'EvaluationClosingPriceDate', w1,
                    'ReviewOeRequired', w4,
                    'ProcAgreement', w4,
                    'ProcAgreementDate', w1,
                    'ProcAsRequired', w4,
                    'ProcAsApproved', w4,
                    'ProcAsApprovedDate', w1,
                    'ProcAsDesc', w0,
                    'FinalConclusionDesc', w0,
                    'WinnerNominationDate', w1,
                    'ObjectionCloseDate', w1,
                    'PoDocName', w0,
                    'TemporaryPic', w0,
                    'PoNumber', w0,
                    'PoDocFile', w0,
                    'F1SubmitDate', w1,
                    'F1SubmitBy', w0,
                    'F2SubmitDate', w1,
                    'F2SubmitBy', w0,
                    'F3SubmitDate', w1,
                    'F3SubmitBy', w0,
                    'F31SubmitDate', w1,
                    'F31SubmitBy', w0,
                    'F4SubmitDate', w1,
                    'F4SubmitBy', w0,
                    'F5SubmitDate', w1,
                    'F5SubmitBy', w0,
                    'F6SubmitDate', w1,
                    'F6SubmitBy', w0,
                    'F7SubmitDate', w1,
                    'F7SubmitBy', w0,
                    'F8SubmitDate', w1,
                    'F8SubmitBy', w0,
                    'F9SubmitDate', w1,
                    'F9SubmitBy', w0,
                    'F10SubmitDate', w1,
                    'F10SubmitBy', w0,
                    'F11SubmitDate', w1,
                    'F11SubmitBy', w0,
                    'F12SubmitDate', w1,
                    'F12SubmitBy', w0,
                    'F13SubmitDate', w1,
                    'F13SubmitBy', w0,
                    'F14SubmitDate', w1,
                    'F14SubmitBy', w0,
                    'F15SubmitDate', w1,
                    'F15SubmitBy', w0,
                    'F16SubmitDate', w1,
                    'F16SubmitBy', w0,
                    'F17SubmitDate', w1,
                    'F17SubmitBy', w0,
                    'F19SubmitDate', w1,
                    'F19SubmitBy', w0,
                    'ProcurementMethodId', w0,
                    'District', w0,
                    'Csms', w0,
                    'MinScore', w0,
                    'ProcRejectTender', w4,
                    'ProcRejectTenderDesc', w0
                ]);
            }
        }
    }
}

